name: CI - VSCode to GitHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lint checks
      run: |
        pip install black pylint
        black --check .
        pylint src/

    - name: Run tests
      run: |
        pip install pytest
        pytest tests/ --maxfail=1 --disable-warnings -q

    - name: Upload coverage result
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
